### ISSUE TITLE
Support a custom timeout when running "slow" commands

### ISSUE THREAD

**Issue by learoyklinginsmith** [redis-rb/redis-cluster-client#286]
### Problem
There are several commands that are run upon connection (COMMAND, CLUSTER SLOTS, CLUSTER NODES) that are considered `@slow` commands. This can increase load on the nodes and in turn, increase latency waiting for a response. We wanted to configure a short timeout for most things but these commands ended up blowing past the timeout really often the first time the connection was used. This ultimately could result in the connection failing on the first use. Additionally, we preconnect all of our redis connections at app startup but that makes the `@slow` commands very slow as we have many clients calling COMMAND at once, which would also cause us to blow past the read timeout.

There was some work done to address this in https://github.com/redis-rb/redis-cluster-client/pull/238 but it seems that as a default, that will only pull information from the primary nodes. In order to include the secondary nodes when running these slow commands, you would need to specify `replica: true`.

### Potential Solutions
There may be a few options to address this:
1. Accept a custom timeout override that's used when running these specific commands. We could theoretically default this to the read timeout so it should be backwards compatible
2. Allow these slow commands to be run on a replica even when `replica: false` (maybe a separate configuration to enable this?)

Hoping to get some thoughts on this. Thanks in advance.

**Comment by supercaracal** [comment]
Thank you for your real-world feedback. I've fixed the former option. Please use the environment variable `REDIS_CLIENT_SLOW_COMMAND_TIMEOUT` if you would like. Also, the portion of the latter option have been fixed with the quick fix. The callings of the `COMMAND` command have become sent to replicas if the scale-read option is enabled. I thought that the behavior, reading from replicas although the scale-read option is disabled, is a bit surprise to users.

* https://github.com/redis-rb/redis-cluster-client/releases/tag/v0.7.4
* https://rubygems.org/gems/redis-cluster-client/versions/0.7.4

**Comment by supercaracal** [comment]
While the second option, the client doesn't know the role each node at initialization. So it's hard to distinguish destination of the command. An environment variable of `REDIS_CLIENT_MAX_STARTUP_SAMPLE` may mitigate the load of the `CLUSTER NODES` command. The environment variable was added in the following pull request.

* #243

**Comment by supercaracal** [comment]
I'll close this issue but I'll reopen it if there are more problems.
